schema_version: "2.0"
mcp_name: "Moroccan Law MCP"
jurisdiction: "MA"

sources:
  - name: "DGSSI Textes législatifs et réglementaires"
    authority: "Direction Générale de la Sécurité des Systèmes d’Information"
    official_portal: "https://www.dgssi.gov.ma/fr/textes-legislatifs-et-reglementaires"
    retrieval_method: "PDF_DOWNLOAD + PDFTOTEXT"
    update_frequency: "periodic"
    last_ingested: "2026-02-21"
    license_or_terms:
      type: "Official government publication terms"
      url: "https://www.dgssi.gov.ma/fr/textes-legislatifs-et-reglementaires"
      summary: "Primary legal text copies and implementing regulations published by Moroccan government authority."
    coverage:
      scope: "Cybersecurity, trust services, electronic transactions, telecommunications, and related decrees"
      limitations: "Image-only PDFs are skipped (OCR disabled by policy) and documented in data/seed/_ingestion-report.json"
    languages:
      - "fr"
      - "ar"

  - name: "Secrétariat Général du Gouvernement (BO portal)"
    authority: "Secrétariat Général du Gouvernement"
    official_portal: "https://www.sgg.gov.ma/BulletinOfficiel.aspx"
    retrieval_method: "Portal research + PDF verification"
    update_frequency: "periodic"
    last_ingested: "2026-02-21"
    license_or_terms:
      type: "Official publication"
      url: "https://www.sgg.gov.ma/BulletinOfficiel.aspx"
      summary: "Official Bulletin Officiel publication source used for legal provenance checks."
    coverage:
      scope: "Official BO publication provenance and cross-checks"
      limitations: "Portal may be unreachable from some runtime environments; inaccessible BO sources are documented as failed/skipped"
    languages:
      - "fr"
      - "ar"

  - name: "OMPIC"
    authority: "Office Marocain de la Propriété Industrielle et Commerciale"
    official_portal: "https://www.ompic.ma"
    retrieval_method: "Direct page fetch"
    update_frequency: "periodic"
    last_ingested: "2026-02-21"
    license_or_terms:
      type: "Official publication"
      url: "https://www.ompic.ma/fr/content/loi-17-97-relative-la-protection-de-la-propriete-industrielle"
      summary: "Official portal for industrial property legislation references."
    coverage:
      scope: "Industrial property and RCC legal references (laws, decrees, and arrêtés)"
      limitations: "Some legacy documents use scanned or non-extractable formats; those records are marked skipped with reason"
    languages:
      - "fr"
      - "ar"

data_freshness:
  automated_checks: true
  check_frequency: "weekly"
  last_verified: "2026-02-21"
